
#Increase melee damage
[strength]
	#Range: > 1
	maxLevel = 10
	prerequisites = ""
	#Range: > 1
	costPerLevel = 110
	#Range: 0.0 ~ 1.7976931348623157E308
	bonusPerLevel = 0.005

#Increase critical chance
[criticalstrike]
	#Range: > 1
	maxLevel = 5
	prerequisites = "strength:1"
	#Range: > 1
	costPerLevel = 110
	#Range: 0.0 ~ 1.0
	bonusPerLevel = 0.005
	#If set to true, vanilla crits will be disabled
	disableVanillaCrits = true

#Increase bow charge speed
[quickdraw]
	#Range: > 1
	maxLevel = 10
	prerequisites = ""
	#Range: > 1
	costPerLevel = 50
	#Range: 0.0 ~ 1.7976931348623157E308
	bonusPerLevel = 0.05

#Increase arrow velocity
[arrowspeed]
	#Range: > 1
	maxLevel = 5
	prerequisites = "quick_draw:1"
	#Range: > 1
	costPerLevel = 110
	#Range: 0.0 ~ 1.7976931348623157E308
	bonusPerLevel = 0.03

#Decrease damage taken
[ironskin]
	#Range: > 1
	maxLevel = 5
	prerequisites = "strength:1"
	#Range: > 1
	costPerLevel = 160
	#Range: 0.0 ~ 1.0
	bonusPerLevel = 0.005

#Increase speed while sneaking
[sneakspeed]
	#Range: > 1
	maxLevel = 5
	prerequisites = ""
	#Range: > 1
	costPerLevel = 80
	#Range: 0.0 ~ 1.7976931348623157E308
	bonusPerLevel = 0.075

#Every X ticks, chance to grow crops around
[greenthumb]
	#Range: > 1
	maxLevel = 10
	prerequisites = ""
	#Range: > 20
	greenThumbTickRate = 100
	#Range: > 1
	costPerLevel = 80
	#Range: 0.0 ~ 1.7976931348623157E308
	bonusPerLevel = 0.015

#Chance to gather extra crops on harvest
[harvestproficiency]
	#Range: > 1
	maxLevel = 10
	prerequisites = "green_thumb:1"
	#Range: > 1
	costPerLevel = 120
	#Range: 0.0 ~ 1.7976931348623157E308
	potentialLootBound = 1.0
	#Range: 0.0 ~ 1.7976931348623157E308
	bonusPerLevel = 0.075

#Chance to gather extra skins from animals
[skinning]
	#Range: > 1
	maxLevel = 5
	prerequisites = ""
	#Range: > 1
	costPerLevel = 80
	#Range: 0.0 ~ 1.7976931348623157E308
	potentialLootBound = 1.0
	#Range: 0.0 ~ 1.7976931348623157E308
	bonusPerLevel = 0.075

#Chance to drop extra meat from animals
[meatgathering]
	#Range: > 1
	maxLevel = 5
	prerequisites = "skinning:1"
	#Range: > 1
	costPerLevel = 70
	#Range: 0.0 ~ 2.147483647E9
	potentialLootBound = 1.0
	#Range: 0.0 ~ 1.7976931348623157E308
	bonusPerLevel = 0.05

#Increase speed under water
[swimspeed]
	#Range: > 1
	maxLevel = 5
	prerequisites = ""
	#Range: > 1
	costPerLevel = 110
	#Range: 0.0 ~ 1.7976931348623157E308
	bonusPerLevel = 0.125

#Decrease total cooking time
[cookingspeed]
	#Range: > 1
	maxLevel = 5
	prerequisites = ""
	#Range: > 1
	costPerLevel = 110
	#Range: 0.0 ~ 1.0
	bonusPerLevel = 0.09

#Increase stone mining speed
[stonecutting]
	#Range: > 1
	maxLevel = 10
	prerequisites = ""
	#Range: > 1
	costPerLevel = 70
	#Range: 0.0 ~ 1.7976931348623157E308
	bonusPerLevel = 0.05

#Chance to increase yield from ores
[prospecting]
	#Range: > 1
	maxLevel = 5
	prerequisites = "stonecutting:1"
	#Range: > 1
	costPerLevel = 110
	#Range: 0.0 ~ 1.7976931348623157E308
	potentialLootBound = 1.0
	#Range: 0.0 ~ 1.7976931348623157E308
	bonusPerLevel = 0.075

#Increase wood chopping speed
[woodcutting]
	#Range: > 1
	maxLevel = 20
	prerequisites = ""
	#Range: > 1
	costPerLevel = 50
	#Range: 0.0 ~ 1.7976931348623157E308
	bonusPerLevel = 0.05

#Random chance to find treasure while digging
[treasurehunting]
	#Range: > 1
	maxLevel = 5
	prerequisites = "prospecting:3,stonecutting:8"
	#Range: > 1
	costPerLevel = 110
	#Range: > 1
	uncommonTreasureWeight = 3
	#Range: > 1
	commonTreasureWeight = 6
	#Range: > 1
	rareTreasureWeight = 1
	#Range: 0.0 ~ 1.7976931348623157E308
	bonusPerLevel = 0.0125

#Decrease fall damage taken
[softlanding]
	#Range: > 1
	maxLevel = 5
	prerequisites = ""
	#Range: > 1
	costPerLevel = 110
	#Range: 0.0 ~ 1.7976931348623157E308
	bonusPerLevel = 0.035

#Increase movement speed while sprinting
[sprintspeed]
	#Range: > 1
	maxLevel = 5
	prerequisites = ""
	#Range: > 1
	costPerLevel = 110
	#Range: 0.0 ~ 1.7976931348623157E308
	bonusPerLevel = 0.05

