
#Server to Client synced configuration settings
["Damage System"]
	#Max health of the Body
	#Range: 2 ~ 12
	maxHealthBody = 6
	#True if the body can cause death if health drops to 0
	causeDeathBody = true
	#True if the head can cause death if health drops to 0
	causeDeathHead = true
	#Max health of the Head
	#Range: 2 ~ 12
	maxHealthHead = 6
	#Max health of the Right Leg
	#Range: 2 ~ 12
	maxHealthRight_Leg = 6
	#Max health of the Left Leg
	#Range: 2 ~ 12
	maxHealthLeft_Leg = 6
	#Max health of the Left Foot
	#Range: 2 ~ 12
	maxHealthLeft_Foot = 6
	#Max health of the Right Arm
	#Range: 2 ~ 12
	maxHealthRight_Arm = 6
	#Max health of the Right Foot
	#Range: 2 ~ 12
	maxHealthRight_Foot = 6
	#Max health of the Left Arm
	#Range: 2 ~ 12
	maxHealthLeft_Arm = 6

["Locational Armor"]

	["Locational Armor".Toughness]
		#The multiplier for local armor for every armor of slot Legs
		#Range: 1.0 ~ 16.0
		multiplierLegs = 3.0
		#The multiplier for local armor for every armor of slot Head
		#Range: 1.0 ~ 16.0
		multiplierHead = 4.0
		#The multiplier for local armor for every armor of slot Chest
		#Range: 1.0 ~ 16.0
		multiplierChest = 3.0
		#The static offset applied to any armor piece with a value greater than zero of slot Legs
		#Range: 0.0 ~ 4.0
		offsetLegs = 0.0
		#The static offset applied to any armor piece with a value greater than zero of slot Head
		#Range: 0.0 ~ 4.0
		offsetHead = 0.0
		#The multiplier for local armor for every armor of slot Feet
		#Range: 1.0 ~ 16.0
		multiplierFeet = 3.5
		#The static offset applied to any armor piece with a value greater than zero of slot Chest
		#Range: 0.0 ~ 4.0
		offsetChest = 0.0
		#The static offset applied to any armor piece with a value greater than zero of slot Feet
		#Range: 0.0 ~ 4.0
		offsetFeet = 0.0

	["Locational Armor".Armor]
		#The multiplier for local armor for every armor of slot Legs
		#Range: 1.0 ~ 16.0
		multiplierLegs = 3.0
		#The multiplier for local armor for every armor of slot Head
		#Range: 1.0 ~ 16.0
		multiplierHead = 6.0
		#The multiplier for local armor for every armor of slot Chest
		#Range: 1.0 ~ 16.0
		multiplierChest = 2.5
		#The static offset applied to any armor piece with a value greater than zero of slot Legs
		#Range: 0.0 ~ 4.0
		offsetLegs = 0.0
		#The static offset applied to any armor piece with a value greater than zero of slot Head
		#Range: 0.0 ~ 4.0
		offsetHead = 1.0
		#The multiplier for local armor for every armor of slot Feet
		#Range: 1.0 ~ 16.0
		multiplierFeet = 6.0
		#The static offset applied to any armor piece with a value greater than zero of slot Chest
		#Range: 0.0 ~ 4.0
		offsetChest = 0.0
		#The static offset applied to any armor piece with a value greater than zero of slot Feet
		#Range: 0.0 ~ 4.0
		offsetFeet = 0.0

	["Locational Armor"."Internal Healing"]

		["Locational Armor"."Internal Healing".plaster]
			#The time it takes for a single heal to trigger. Total time this item is active = this * totalHeals
			#Range: 1 ~ 32767
			secondsPerHeal = 2
			#The time it takes in the GUI to apply the item in milliseconds
			#Range: 0 ~ 16000
			applyTime = 2000
			#The total heals this item does when applied. 1 heal = half a heart
			#Range: 1 ~ 127
			totalsHeals = 3

		["Locational Armor"."Internal Healing".bandage]
			#The time it takes for a single heal to trigger. Total time this item is active = this * totalHeals
			#Range: 1 ~ 32767
			secondsPerHeal = 4
			#The time it takes in the GUI to apply the item in milliseconds
			#Range: 0 ~ 16000
			applyTime = 3000
			#The total heals this item does when applied. 1 heal = half a heart
			#Range: 1 ~ 127
			totalsHeals = 6

	["Locational Armor"."External Healing"]
		#The value vanilla's natural regeneration will be multiplied with. Has no effect if "allowNaturalRegeneration" is disabled
		#Range: 0.0 ~ 20.0
		naturalRegenMultiplier = 0.5
		#Allow vanilla's natural regeneration. Requires "allowOtherHealingItems" to be true
		#**WARNING** This sets the gamerule "naturalRegeneration" for all of your worlds internally, so it persists even if you remove the mod
		allowNaturalRegeneration = false
		#If false, healing potions and other healing items will have no effect
		allowOtherHealingItems = true
		#Specifies how much percent of the max health should be restored when sleeping
		#Range: 0.0 ~ 1.0
		sleepHealPercentage = 0.5
		#The value external regen will be multiplied with. Has no effect if "allowOtherHealingItems" is disabled
		#Range: 0.0 ~ 20.0
		otherRegenMultiplier = 0.75

	["Locational Armor".misc]
		#If true, max health will be capped at 6 hearts and absorption at 2 hearts per limb. If false, the health cap will be much higher (64 hearts normal and 16 absorption)
		capMaxHealth = true
		#If set to LOCAL_ENCHANTMENTS, only the enchantments for the armor for the body part that is currently being damaged is taken into account. The strength of the armor is multiplied by 4, so it matches the vanilla default
		#If set to GLOBAL_ENCHANTMENTS, the enchantments of all armor pieces are taken into account for all body parts that have any kind of armor.
		#Allowed Values: GLOBAL_ENCHANTMENTS, LOCAL_ENCHANTMENTS
		armorEnchantmentMode = "LOCAL_ENCHANTMENTS"
		#If true, max health is scaled to your hearts, and the config entries get multiplier to match the max health
		scaleMaxHealth = true
		#If enabled, the default random damage distribution will be changed to leave critical limbs at 1hp if possible.
		#When there is too much damage, the damage will still kill the player. Other distributions that defined are not affected by this.
		useFriendlyRandomDistribution = false
		#Specifies how the vanilla health is calculated. Affects the vanilla visual health bar, as well as the value other mods get to see when they query the player health.
		#AVERAGE_ALL simply takes all limbs and calculates the average of it.
		#AVERAGE_CRITICAL takes all critical limbs and calculates the average of it.
		#MIN_CRITICAl takes the smallest health value of all critical limb.
		#Does not have any effect if all critical limbs have been disabled.
		#Allowed Values: AVERAGE_ALL, AVERAGE_CRITICAL, MIN_CRITICAL, CRITICAL_50_PERCENT_OTHER_50_PERCENT
		vanillaHealthCalculation = "AVERAGE_ALL"

