
["Damage Enchantments"]
	# The maximum enchantment level
	#Range: 1 ~ 10
	maxLevel = 10
	# Whether the mod changes these enchantments
	isEnabled = true

[Efficiency]
	# The maximum enchantment level
	#Range: 1 ~ 10
	maxLevel = 10
	# Whether the mod changes these enchantments
	isEnabled = true

["Fire Aspect"]
	# The maximum enchantment level
	#Range: 1 ~ 10
	maxLevel = 10
	# Whether the mod changes these enchantments
	isEnabled = true

[Impaling]
	# The maximum enchantment level
	#Range: 1 ~ 10
	maxLevel = 10
	# Whether the mod changes these enchantments
	isEnabled = true

[Knockback]
	# The maximum enchantment level
	#Range: 1 ~ 10
	maxLevel = 10
	# Whether the mod changes these enchantments
	isEnabled = true

["Loot Bonus Enchantments"]
	# The maximum enchantment level
	#Range: 1 ~ 10
	maxLevel = 10
	# Whether the mod changes these enchantments
	isEnabled = true

[Loyalty]
	# The maximum enchantment level
	#Range: 1 ~ 5
	maxLevel = 5
	# Whether the mod changes these enchantments
	isEnabled = true

[Lure]
	# The maximum enchantment level
	#Range: 1 ~ 5
	maxLevel = 5
	# Whether the mod changes these enchantments
	isEnabled = true

[Piercing]
	# The maximum enchantment level
	#Range: 1 ~ 10
	maxLevel = 10
	# Whether the mod changes these enchantments
	isEnabled = true

[Power]
	# The maximum enchantment level
	#Range: 1 ~ 10
	maxLevel = 10
	# Whether the mod changes these enchantments
	isEnabled = true

["Protection Enchantments"]
	# The maximum enchantment level
	#Range: 1 ~ 10
	maxLevel = 10
	# Whether the mod changes these enchantments
	isEnabled = true

[Punch]
	# The maximum enchantment level
	#Range: 1 ~ 10
	maxLevel = 10
	# Whether the mod changes these enchantments
	isEnabled = true

["Quick Charge"]
	# The maximum enchantment level
	#Range: 1 ~ 5
	maxLevel = 5
	# Whether the mod changes these enchantments
	isEnabled = true

[Respiration]
	# The maximum enchantment level
	#Range: 1 ~ 5
	maxLevel = 5
	# Whether the mod changes these enchantments
	isEnabled = true

[Riptide]
	# The maximum enchantment level
	#Range: 1 ~ 5
	maxLevel = 5
	# Whether the mod changes these enchantments
	isEnabled = true

["Soul Speed"]
	# The maximum enchantment level
	#Range: 1 ~ 5
	maxLevel = 5
	# Whether the mod changes these enchantments
	isEnabled = true

["Sweeping Edge"]
	# The maximum enchantment level
	#Range: 1 ~ 10
	maxLevel = 10
	# Whether the mod changes these enchantments
	isEnabled = true

[Thorns]
	# The maximum enchantment level
	#Range: 1 ~ 10
	maxLevel = 10
	# Whether the mod changes these enchantments
	isEnabled = true

[Unbreaking]
	# The maximum enchantment level
	#Range: 1 ~ 10
	maxLevel = 10
	# Whether the mod changes these enchantments
	isEnabled = true

["Enchanter Villager"]
	# Whether the enchanter villager is enabled
	isEnabled = true

["Attack Reach"]
	# The maximum enchantment level
	#Range: 1 ~ 10
	maxLevel = 1
	# Whether the mod changes these enchantments
	isEnabled = false

["Block Reach"]
	# The maximum enchantment level
	#Range: 1 ~ 10
	maxLevel = 3
	# Whether the mod changes these enchantments
	isEnabled = false

["Cat Vision"]
	# The maximum enchantment level
	#Range: 1 ~ 1
	maxLevel = 1
	# Whether the mod changes these enchantments
	isEnabled = true

[Camouflage]
	# The maximum enchantment level
	#Range: 1 ~ 1
	maxLevel = 1
	# Whether the mod changes these enchantments
	isEnabled = true

[Critical]
	# The maximum enchantment level
	#Range: 1 ~ 5
	maxLevel = 5
	# Whether the mod changes these enchantments
	isEnabled = false

["Cavernous Storage"]
	# The maximum enchantment level
	#Range: 1 ~ 1
	maxLevel = 1
	# Whether the mod changes these enchantments
	isEnabled = false

["Double Break"]
	# The maximum enchantment level
	#Range: 1 ~ 5
	maxLevel = 5
	# Whether the mod changes these enchantments
	isEnabled = false

["Fast Hopper"]
	# The maximum enchantment level
	#Range: 1 ~ 1
	maxLevel = 1
	# Whether the mod changes these enchantments
	isEnabled = true

[Flight]
	# The maximum enchantment level
	#Range: 1 ~ 3
	maxLevel = 3
	# Whether the mod changes these enchantments
	isEnabled = false

[Freezing]
	# The maximum enchantment level
	#Range: 1 ~ 10
	maxLevel = 3
	# Whether the mod changes these enchantments
	isEnabled = true

["Health Boost"]
	# The maximum enchantment level
	#Range: 1 ~ 5
	maxLevel = 3
	# Whether the mod changes these enchantments
	isEnabled = true

[Heavy]
	# The maximum enchantment level
	#Range: 1 ~ 10
	maxLevel = 5
	# Whether the mod changes these enchantments
	isEnabled = true

[Reinforcement]
	# The maximum enchantment level
	#Range: 1 ~ 10
	maxLevel = 5
	# Whether the mod changes these enchantments
	isEnabled = true

[Replanting]
	# The maximum enchantment level
	#Range: 1 ~ 1
	maxLevel = 1
	# Whether the mod changes these enchantments
	isEnabled = true

["Step Assist"]
	# The maximum enchantment level
	#Range: 1 ~ 3
	maxLevel = 3
	# Whether the mod changes these enchantments
	isEnabled = false

[Temper]
	# The maximum enchantment level
	#Range: 1 ~ 10
	maxLevel = 5
	# Whether the mod changes these enchantments
	isEnabled = true

["Fast Smelt"]
	# The maximum enchantment level
	#Range: 1 ~ 5
	maxLevel = 1
	# Whether the mod changes these enchantments
	isEnabled = true

["Fuel Efficient"]
	# The maximum enchantment level
	#Range: 1 ~ 5
	maxLevel = 1
	# Whether the mod changes these enchantments
	isEnabled = true

["Extra Experience"]
	# The maximum enchantment level
	#Range: 1 ~ 5
	maxLevel = 1
	# Whether the mod changes these enchantments
	isEnabled = true

["Heavy Blade"]
	# The maximum enchantment level
	#Range: 1 ~ 5
	maxLevel = 5
	# Whether the mod changes these enchantments
	isEnabled = true

["Light Blade"]
	# The maximum enchantment level
	#Range: 1 ~ 5
	maxLevel = 3
	# Whether the mod changes these enchantments
	isEnabled = true

[Blindness]
	# The maximum enchantment level
	#Range: 1 ~ 1
	maxLevel = 1
	# Whether the mod changes these enchantments
	isEnabled = true

["Fire Resistance"]
	# The maximum enchantment level
	#Range: 1 ~ 1
	maxLevel = 1
	# Whether the mod changes these enchantments
	isEnabled = true

[Haste]
	# The maximum enchantment level
	#Range: 1 ~ 5
	maxLevel = 3
	# Whether the mod changes these enchantments
	isEnabled = true

[Hunger]
	# The maximum enchantment level
	#Range: 1 ~ 5
	maxLevel = 3
	# Whether the mod changes these enchantments
	isEnabled = true

[Invisibility]
	# The maximum enchantment level
	#Range: 1 ~ 1
	maxLevel = 1
	# Whether the mod changes these enchantments
	isEnabled = true

["Jump Boost"]
	# The maximum enchantment level
	#Range: 1 ~ 5
	maxLevel = 3
	# Whether the mod changes these enchantments
	isEnabled = true

["Mining Fatigue"]
	# The maximum enchantment level
	#Range: 1 ~ 5
	maxLevel = 3
	# Whether the mod changes these enchantments
	isEnabled = true

[Nausea]
	# The maximum enchantment level
	#Range: 1 ~ 1
	maxLevel = 1
	# Whether the mod changes these enchantments
	isEnabled = true

[Poison]
	# The maximum enchantment level
	#Range: 1 ~ 5
	maxLevel = 3
	# Whether the mod changes these enchantments
	isEnabled = true

[Regeneration]
	# The maximum enchantment level
	#Range: 1 ~ 5
	maxLevel = 3
	# Whether the mod changes these enchantments
	isEnabled = true

[Resistance]
	# The maximum enchantment level
	#Range: 1 ~ 4
	maxLevel = 3
	# Whether the mod changes these enchantments
	isEnabled = true

[Saturation]
	# The maximum enchantment level
	#Range: 1 ~ 5
	maxLevel = 3
	# Whether the mod changes these enchantments
	isEnabled = true

["Slow Falling"]
	# The maximum enchantment level
	#Range: 1 ~ 1
	maxLevel = 1
	# Whether the mod changes these enchantments
	isEnabled = true

[Slowness]
	# The maximum enchantment level
	#Range: 1 ~ 3
	maxLevel = 3
	# Whether the mod changes these enchantments
	isEnabled = true

[Speed]
	# The maximum enchantment level
	#Range: 1 ~ 5
	maxLevel = 3
	# Whether the mod changes these enchantments
	isEnabled = true

[Strength]
	# The maximum enchantment level
	#Range: 1 ~ 5
	maxLevel = 3
	# Whether the mod changes these enchantments
	isEnabled = true

["Water Breathing"]
	# The maximum enchantment level
	#Range: 1 ~ 1
	maxLevel = 1
	# Whether the mod changes these enchantments
	isEnabled = true

[Weakness]
	# The maximum enchantment level
	#Range: 1 ~ 3
	maxLevel = 3
	# Whether the mod changes these enchantments
	isEnabled = true

