
#General settings
[general]
	#Does disenchanting cost xp?
	requires_xp = false
	#Should the disenchanter select a random enchantment to disenchant?
	random_enchantment = false
	#Relative scale of how much XP the disenchanter costs to use (lower requires less XP)
	#Range: 1 ~ 10
	xp_cost = 1

