
["Enable or Disable Enchantments"]
	enhanced_protection = true
	feasting = true
	delicate = true
	enhanced_unbreaking = true
	Frostbite = true
	enhanced_handling = true
	enhanced_sharpness = true
	lifestealing_arrows = true
	night_vision_ench = true
	decay = true
	final_stand = true
	springy = true
	ground_pound = true
	blessed_weapon = true
	dull_edge = true
	fiery_thorns = true
	vitality = true
	enhanced_fire_aspect = true
	enhanced_locomotion = true
	enhanced_thorns = true
	tnt_miner = true
	lightning = true
	"XP++ for Weapon" = true
	webbing = true
	water_breathing = true
	jugger_nog = true
	enhanced_efficiency = true
	praise_the_sun = true
	slowness = true
	"XP++ for Tool" = true
	exploding_arrows = true
	heavy = true
	savior = true
	horse_shoe = true
	disengage = true
	"/cleargrounditems command" = true
	insta_kill = true
	wither = true

